image:
  - Visual Studio 2017

# branches to build
branches:
  only:
    - dev

# environments
environment:
  matrix:
    - ARCH: Win64
      TOOLSET: msbuild
      CONFIGURATION: Release
    - ARCH: Win32
      TOOLSET: msbuild
      CONFIGURATION: Release
# clone directory
clone_folder: c:\projects\sqlite3enc

before_build:
  # set environment variables for SQLite3Enc
  - set LIBICU_PATH=C:\ICU_DATA
  - ps: Start-FileDownload  'https://github.com/unicode-org/icu/releases/download/release-64-2/icu4c-64_2-data.zip'
  - ps: Start-FileDownload 'https://github.com/unicode-org/icu/releases/download/release-64-2/icu4c-64_2-Win32-MSVC2017.zip'
  - ps: Start-FileDownload 'https://github.com/unicode-org/icu/releases/download/release-64-2/icu4c-64_2-Win64-MSVC2017.zip'
  - cmd: 7z x -y icu4c-64_2-Win32-MSVC2017.zip -o%LIBICU_PATH%
  - cmd: 7z x -y icu4c-64_2-Win64-MSVC2017.zip -o%LIBICU_PATH%
  - cmd: 7z x icu4c-64_2-data.zip -o%LIBICU_PATH%
  - cmd: del icu4c-64_2-Win32-MSVC2017.zip && del icu4c-64_2-Win64-MSVC2017.zip && del icu4c-64_2-data.zip
  - cmd: c:\projects\sqlite3enc\premake.bat --builddir=build vs2017

# build script
build_script:
  - cmd: c:\projects\sqlite3enc\admin\appveyor\appveyor.bat

after_build:
  - cmd: cd c:\projects\sqlite3enc
  - cmd: 7z a -tzip SQLite3-Encryption_%ARCH%-v%APPVEYOR_BUILD_VERSION%.zip bin-vc15/ -xr@x_fn.txt
  - ps: Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
#
deploy:
   description: 'Automatically deployed release'
   provider: GitHub
   auth_token:
    secure: wZ049LmzjlMHqV5IFklperAW7uhpMllxePBaf+ZUK5IWJQGsPEY8pCsmTw+Yck4d
   draft: false
   prerelease: false
   on:
      branch: dev
   appveyor_repo_tag: true

on_success:
- ps: >-
    if ($true)

    {
      Write-Host "Success"
    }
